config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'pesquisas#index'

  resources :notas
  resources :pesquisas
  resources :users
  resources :membros
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/membro.rb
class Membro < ApplicationRecord
    belongs_to :pesquisa
    belongs_to :user

    after_create :send_confirmation

    def self.save_and_create_user params
        @user = User.find_or_create(params)
        @member = Membro.create({
            pesquisa_id: params[:pesquisa_id], 
            respondeu: false,
            user_id: @user.id
        })
    end

    def membro_respondeu?
        respondeu
    end

    private 
    def send_confirmation
        MembroMailer.with(membro: self, id: self.id).confirmation.deliver_now
    end
end

app/models/nota.rb
class Nota < ApplicationRecord
    belongs_to :pesquisa

    before_update :is_blocked

    private
    
    def is_blocked
        throw(:abort) if pesquisa.encerrada
    end
end

app/models/pesquisa.rb
class Pesquisa < ApplicationRecord
    has_many :notas
    has_many :membros

    accepts_nested_attributes_for :notas

    validates_presence_of :pergunta

    before_update :is_blocked

    def media
        notas.average(:valor)
    end

    def self.create_nota nota
        
        @nota = Nota.new()
        @nota.pesquisa_id = nota[:id]
        @nota.valor = nota[:pesquisa][:valor]
        @nota.save
    end

    private
    def is_blocked
        throw(:abort) if self.encerrada
    end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :membros
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   def self.find_or_create params
    @user = User.find_by_email params[:email]

    raise 'Email já cadastrado, tente outro email' if @user

    unless @user.present?
      @user = User.create({nome: params[:nome],email: params[:email], admin: params[:admin], password: '123456'})
    end
    @user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/membros_controller.rb
class MembrosController < ApplicationController
  before_action :set_membro, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  def index
    @membros = Membro.all
  end

  def new
    @membro = Membro.new
  end

  def show 
  end

  def create 
    @membro = Membro.save_and_create_user(membro_params)

    respond_to do |format|
      if @membro.save
        format.html { redirect_to @membro, notice: 'membro was successfully created.' }
        format.json { render :show, status: :created, location: @membro }
      else
        format.html { render :new }
        format.json { render json: @membro.errors, status: :unprocessable_entity }
      end
    end


  end
  def update
    raise 'Procedimento não permitido' if @membro.nil?
    @user = User.find(@membro.user_id)
    @user.update_attributes({email: params[:email], admin: params[:admin], nome: params[:nome]})
    respond_to do |format|
      if @membro.update(membro_params)
        format.html { redirect_to @membro, notice: 'membro was successfully updated.' }
        format.json { render :show, status: :ok, location: @membro }
      else
        format.html { render :edit }
        format.json { render json: @membro.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    raise 'Procedimento não permitido' if @membro.nil? || @membro.user.id == current_user.id
    @user = User.find @membro.user_id
    @membro.destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to membros_url, notice: 'membro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_membro
  #  authorize 
   @membro = Membro.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def membro_params
    params.require(:membro).permit(:nome, :email, :pesquisa_id)
  end

end

app/controllers/notas_controller.rb
class NotasController < ApplicationController
  before_action :set_nota, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @notas = Nota.all
  end

  def new
    @nota = Nota.new
  end

  def create 
    @nota = Nota.new(pesquisa_params)

    respond_to do |format|
      if @nota.save
        format.html { redirect_to @nota, notice: 'pesquisa was successfully created.' }
        format.json { render :show, status: :created, location: @nota }
      else
        format.html { render :new }
        format.json { render json: @nota.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @nota.update(pesquisa_params)
        format.html { redirect_to @nota, notice: 'pesquisa was successfully updated.' }
        format.json { render :show, status: :ok, location: @nota }
      else
        format.html { render :edit }
        format.json { render json: @nota.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @nota.destroy
    respond_to do |format|
      format.html { redirect_to notas_url, notice: 'pesquisa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_nota
  #  authorize 
   @nota = Nota.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def nota_params
    params.require(:nota).permit(:nota, :pesquisa_id)
  end
end

app/controllers/pesquisas_controller.rb
class PesquisasController < ApplicationController
  before_action :set_pesquisa, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  def index
    @pesquisas = Pesquisa.all
  end

  def new
    @pesquisa = Pesquisa.new
  end

  def show 
  end

  def create 
    @pesquisa = Pesquisa.new(pesquisa_params)

    respond_to do |format|
      if @pesquisa.save
        format.html { redirect_to @pesquisa, notice: 'pesquisa was successfully created.' }
        format.json { render :show, status: :created, location: @pesquisa }
      else
        format.html { render :new }
        format.json { render json: @pesquisa.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    @member = Membro.find_by_user_id current_user.id
    raise 'Usuário já votou.' if @member.membro_respondeu?

    Pesquisa.create_nota(notas_attributes.slice(:pesquisa, :id))
    respond_to do |format|
      if @pesquisa.save
        @member.update_attributes(respondeu: true)
        format.html { redirect_to @pesquisa, notice: 'pesquisa was successfully updated.' }
        format.json { render :show, status: :ok, location: @pesquisa }
      else
        format.html { render :edit }
        format.json { render json: @pesquisa.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pesquisa.destroy
    respond_to do |format|
      format.html { redirect_to pesquisas_url, notice: 'pesquisa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_pesquisa
  #  authorize 
   @pesquisa = Pesquisa.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pesquisa_params
    params.require(:pesquisa).permit(:pergunta)
  end
  
  def notas_attributes
    request.parameters
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/membros_helper.rb
module MembrosHelper
end

app/helpers/nota_helper.rb
module NotaHelper
end

app/helpers/pesquisa_helper.rb
module PesquisaHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HappyNel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <% @usuario = current_user  %>
  <% if !user_signed_in?%>
    <%= render partial: "layouts/logout" %>
  <% end %>

  <body class="text-center">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/pesquisas">HappyNel</a>
    <% if user_signed_in?%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <% if @usuario.admin? %>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/pesquisas">Dashboard</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/membros">Membros</a>
          </li>
        </ul>
      </div>
    <%end%>
    <%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></br>
    <%end%>
    <span class="navbar-text">
    </span>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/membros/_form.html.erb
<%= form_with(model: membro, local: true) do |form| %>
  <form>
    <div class="form-group">
      <label for="pergunta">Pergunta</label>
      <%=form.text_field :nome, 
	           placeholder: 'nome', 
	           class: 'form-control'%>
      <%= form.text_field :email, 
	           placeholder: 'email', 
	           class: 'form-control' %>
      <% perguntas_array = Pesquisa.all.map { |pesquisa|
          [pesquisa.pergunta, pesquisa.id] } %>
      <%= form.select(:pesquisa_id, 
          options_for_select(perguntas_array)) %>
      <div>
      <%=form.radio_button(:admin, "Admin?")%>
      <label for="admin?">É admin?</label>
      </div>
    </div>
    <%= form.submit "Salvar", class: "btn btn-primary" %>
  </form>
<% end %>   

app/views/membros/destroy.html.erb
<h1>Membros#destroy</h1>
<p>Find me in app/views/membros/destroy.html.erb</p>

app/views/membros/edit.html.erb
<h1>Membros#edit</h1>
<p>Find me in app/views/membros/edit.html.erb</p>

app/views/membros/index.html.erb
<div class="container-fluid">
  <p><h3>Membros</h3></p>

  <p>
    <button type="button" class="btn btn-outline-primary"><%= link_to 'Novo membro', new_membro_path() %></button>
  </p>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Nome</th>
        <th scope="col">E-mail</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
       <% @membros.each do |membro| %>
      <tr>
        <td><%= membro.user.nome %></td>
        <td><%= membro.user.email %></td>
        <td><%= link_to 'Mostar', membro, :class => 'btn btn-success btn-sm' %>|
        <%= link_to 'Editar', edit_membro_path(membro), :class => 'btn btn-warning btn-sm' %>|
        <%= link_to 'Apagar', membro, :class => 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

    </tbody>
  </table>
</div>
  

app/views/membros/new.html.erb
<div class="container-fluid">
    <h3>Nova Membro</h3>

    <%= render 'form', membro: @membro %>

    <%= link_to 'Voltar', membros_path %>
</div>

app/views/membros/show.html.erb
<h1>Membros#show</h1>
<p>Find me in app/views/membros/show.html.erb</p>

app/views/membros/update.html.erb
<h1>Membros#update</h1>
<p>Find me in app/views/membros/update.html.erb</p>

app/views/notas/index.html.erb
<div class="container-fluid">
  <p><h3>Pesquisas</h3></p>

  <p>
    <button type="button" class="btn btn-outline-primary"><%= link_to 'Nova enquete', new_pesquisa_path() %></button>
  </p>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th colspan="2" scope="col">Pesquisa</th>
        <th scope="col">Média</th>
      </tr>
    </thead>
    <tbody>
       <% @pesquisas.each do |pesquisa| %>
      <tr>
        <td><%= pesquisa.code %></td>
        <td><%= pesquisa.media %></td>
        <td><%= link_to 'Mostar', pesquisa, :class => 'btn btn-success btn-sm' %></td>
        <td><%= link_to 'Editar', edit_pesquisa_path(pesquisa), :class => 'btn btn-warning btn-sm' %></td>
        <td><%= link_to 'Apagar', pesquisa, :class => 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

    </tbody>
  </table>
</div>

app/views/notas/new.html.erb
    <button type="button" class="btn btn-outline-primary"><%= link_to 'Início', welcome_index_path() %></button>

app/views/pesquisas/_form.html.erb
<%= form_with(model: pesquisa, local: true) do |form| %>
  <form>
    <div class="form-group">
      <label for="pergunta">Pergunta</label>
      <%=form.text_field :pergunta,
          class: "form-control",
          placeholder: "Default input"%>
    </div>
    <%= form.submit "Salvar", class: "btn btn-primary" %>
  </form>
<% end %>   

app/views/pesquisas/edit.html.erb
<div class="container-fluid">
  <%= form_with(model: @pesquisa, local: true) do |form| %>
    <%=@pesquisa.pergunta%>
    <p>
      <%= form.select(:valor, 
          options_for_select(0..10)) 
          %>
    </p>
    <p>
      <%= form.submit "Salvar", class: "btn btn-primary" %>
    </p>
  <%end%>
</div>

app/views/pesquisas/index.html.erb
<div class="container-fluid">
  <p><h3>Pesquisas</h3></p>

  <p>
    <button type="button" class="btn btn-outline-primary"><%= link_to 'Nova enquete', new_pesquisa_path() %></button>
  </p>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Pesquisa</th>
        <th scope="col">Média</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
       <% @pesquisas.each do |pesquisa| %>
      <tr>
        <td><%= pesquisa.pergunta %></td>
        <td><%= pesquisa.media %></td>
        <td><%= link_to 'Mostar', pesquisa, :class => 'btn btn-success btn-sm' %>|
        <%= link_to 'Apagar', pesquisa, :class => 'btn btn-danger btn-sm', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

    </tbody>
  </table>
</div>

app/views/pesquisas/new.html.erb
<div class="container-fluid">
    <h3>Nova Pesquisa</h3>

    <%= render 'form', pesquisa: @pesquisa %>

    <%= link_to 'Voltar', pesquisas_path %>
</div>

app/views/pesquisas/show.html.erb
<p>
  <strong>Pergunta:</strong>
  <%= @pesquisa.pergunta %>
</p>